### ISSUE TITLE
Advanced Export - numeric inputs & some predefined colors

### ISSUE THREAD

**Issue by przemowcf** [Pictogrammers/pictogrammers.com#37]
Hi,
Some more suggestions 😄 

### 1.
I would like to point out that those "sliders" are annoying (like try sliding it to 16px, and do it multiple times 💢 for different icons 😑 ),  I would like to suggest adding beside sliders (like it was in old version) - numeric input field where I just can type e.g. size in px (from 8px at least 😉  ), for:
- size,
- padding,
- rotate (?),
- corner radius (?).

### 2.
Can I ask to restore in color pickers: some predefined colors  - like it was in old version? Those were really helpful, I just clicked color and was done, now I have to copy-pase color for every icon I want to download 😑 ...

*Ps. Sorry for being annoying, just my workflow got busted by killing old materialdesignicons.com 😩 , I think you should add some big banner that old page will be shut down, with link to new one (and like no updates, etc...), and work on pictogramemrs.com in mean time - so you could just swap it at some point when it'll be considered ready (all functions, features from old + new ones are finished&working).* 

*Right now, this how I feel about this swap: It's like something M$ would do: "just forcefully push new os to users , and let's wait for their **feedback** (mildly speaking) what we forget to do..." - I am sorry, this how I feel about it right now* 😞

**Comment by mririgoyen** [comment]
We can consider both of those things. However, for your second suggestion, the "predefined" colors is really going to be subjective and limited. I'm not sure exactly what you're looking for here, but you're looking at, at most, 16 predefined colors to choose from. I don't know how helpful that will be, but we can do it.

Example:
<img width="234" alt="Screenshot 2023-01-30 at 8 48 37 AM" src="https://user-images.githubusercontent.com/1015040/215509742-62309191-5866-4ab3-bcd7-b0bec2c8c065.png">

---

I'm more interested in hearing about your "workflow" though. It sounds like you do this often and, to be honest, you really shouldn't! Why are you creating PNG versions of the icons instead of using the vector equivalents, especially en masse? Tell us about what you're doing and why and let's see if there is a better way that can help save you time and effort. We have lots of tooling and ways to get the icons, so I'm sure we can find an easier way.

To address your comment about the launch of the new site, [it was actually announced nearly 3 years ago](https://github.com/Templarian/MaterialDesign/issues/5161). 😄 We've made changes to the site based on analytics, user feedback, and industry trends. For example, we removed raster-based Android icons downloads and only offer vector-based because that is the recommendation moving forward. Simplifying and taking emphasis off the Advanced Export feature is another decision we made; you really should be using SVGs everywhere these days. We want to promote the options and techniques that keep up with the changing landscape of design and development.

We do appreciate your feedback and will look into addressing your two suggestions in the meantime.

**Comment by saper-2** [comment]
I think predefined palette mean that old one: 
![image](https://user-images.githubusercontent.com/8533673/215575301-f1ac4d05-c62e-4b38-9759-54361d8daf53.png)

I've been using it too, "far more handy" than sliders, and no need to remember hex/rgb (or ```Ctrl+C / Ctrl+V```) just click that same "color" 😉 .


*This is from my point of view, and for what I'm using MDI.*

Maybe 'workflow' - mean using MDI in e.g. winForms applications (I'm using MDI too in .netFW winForms programs) - you can't use svg at all (in winforms), at best PNG 😄. 

Recently I was writing small app , and I was going back an forth to materialdesignicons looking for icons that would symbolize what I wanted - I didn't want to write a whole sentence on button 😅 , and of course those I have to have in PNG.

I am either no android, nor web dev, like I mentioned, I write for windows (winforms , I don't use other technologies because I know it good and it's sufficient for my requirements) - so in those two any graphic are mainly in png (or bmp/jpg). I do know php/html/css/js but only as much I need (for project/for simple UI/etc.. I don't need fancy frameworks (which docs can overheat my brain 😄 )).

Personally, I didn't even know there is going new page until it was swapped 😑 - I don't remember even seeing any notice on main page - I only was aware about github for icons (it helped me few times to find some icons).

**Comment by mririgoyen** [comment]
The changes to the color picker and the addition of the input boxes next to the sliders are now live. Thank you for your feedback.

**Comment by przemowcf** [comment]
@mririgoyen  Thanks! 👍  

Additional wish from me 😄 : could be possible add 3rd row where color I can set&save own color (it would be saved in cookie in webbrowser)?

And yes, like @saper-2 mentioned, I do use MDI in winForms apps too, so I'm basically stuck on PNG, and sometimes picking right icon for the job can take few attempts 😉

**Comment by mririgoyen** [comment]
Maybe in the future, we can look to expand Advanced Export's feature set. However, at the moment, we're happy with what we are offering and we have other things we need to spend time on. Of course, you're more than welcome to add that functionality and open a PR! 😄 

In terms of the WinForms, afaik, Microsoft has put the project into Maintenance Mode. I know its successor, WPF, supports XAML images, which we offer as a download option. There are also other alternatives with higher adoption rates, such as Delphi VCL (which supports SVGs). What I'm getting at is, spending lots of development cycles on our end to support a niche use case that is on the decline isn't that productive for us. But as I said, we are open to PRs.
