### ISSUE TITLE
Can't tell which icons are from Material or from the Community

### ISSUE THREAD

**Issue by eddieshowcase** [Pictogrammers/pictogrammers.com#39]
Your new website for material design icons looks nice.

However, one of the things I relied on or found quite useful on the old site was the red border highlight/outline around icons that indicated the icon was a community icon. I was nice to to be able to see what the core Material icon was when searching, but then being able to see the community additions and variants related to a particular search of keyword(s).

I request that you add a similar indication on the new site.

**Comment by mririgoyen** [comment]
Hi, thanks for the kind words about the new site.

We intentionally do not call out icon's author on the main library view because we believe that all contributors are equally important and all icons are equally beautiful. Additionally, just because Google was the main source of inspiration for the icons in the Material Design Icons library, we do not include all of their icons, regularly replace theirs with ones we feel convey meaning in a better way, and Google does not contribute to our other icon libraries.

If you're interested in the author of an icon, when you click on an icon, the author is listed next to the release version. You can click on the author to see all icons that author created on their contributor profile page.

<img width="362" alt="Screenshot 2023-01-30 at 3 44 59 PM" src="https://user-images.githubusercontent.com/1015040/215602278-f97586c9-ed5a-45f1-b3d9-514d287a0141.png">

You can also use the global site search or visit the [Contributors](https://pictogrammers.com/docs/contribute/contributors/) page to find a specific contributor, such as Google, to see all icons created by them.
