### ISSUE TITLE
[pixel-editor]: add path reset button

### ISSUE THREAD

**Issue by andrejsharapov** [Pictogrammers/pictogrammers.com#47]
### Describe your suggested feature

1. I think it's worth adding a button to reset the entire path. It will be more convenient than erasing one cell at a time.

![image](https://user-images.githubusercontent.com/44722574/216668661-75f1bfb5-922f-43aa-9c32-31916b6b5ccf.png)

2. For handleMouseMove, there is only the addition of points, but there is no way to erase them.

**Comment by mririgoyen** [comment]
This is actually just a very, early prototype. @Templarian is working on the full-fledged editor. Perhaps he can give a status update when he has time. 😄

**Comment by Templarian** [comment]
@andrejsharapov This is being developed into a full fledged editor. I put a proof of concept up below.

https://pictogrammers.github.io/@pictogrammers/pixel-editor/

- The demo above resize canvas is broken (fixed it locally already).
- The demo above the open button is broken due to the api moving to another domain.
- Have a lot more changes locally that I'll work to push out this weekend. Rewriting the UI right now from scratch.

**Comment by Templarian** [comment]
@andrejsharapov Pushed more changes. I'll keep this thread open until I have all the features flushed out with the ability to create contributions from the UI. Then we'll replace that page with a link to the application.

**Comment by Templarian** [comment]
Closing this one as I'll handle everything over in the https://github.com/Pictogrammers/Pixel-Editor repo now.
