### ISSUE TITLE
Pressing enter in the search box replaces the text with `undefined`

### ISSUE THREAD

**Issue by abextm** [Pictogrammers/pictogrammers.com#51]
### Before You Begin

- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Pressing enter in the search box replaces the text with `undefined` and does not search anything

### Describe the behavior you expected

Pressing enter navigates you to a full search result page

### Steps to reproduce the issue

1. Press enter in the search box
2. It is now undefined

### Which browser are you experiencing the issue?

Firefox nightly 111.0a1 (2023-01-31) & Chrome 109.0.5414.74

### Which operating system are you using to run this browser?

Arch Linux

**Comment by mririgoyen** [comment]
Thanks for the report. I've made changes so that when you press "Enter" in the search box, you do not lose your search term. The search mechanism happens as you type, so you should see the results directly beneath the search box in real-time. It's possible typing quickly and pressing Enter was hiding that fact, so with the changes I made, it should be more apparent.

Changes should be deployed in about an hour.
